apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alertaggregator.fullname" . }}
  labels:
    helm.sh/chart: {{ include "alertaggregator.chart" . }}
    app.kubernetes.io/name: {{ include "alertaggregator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}