{{if .Values.global.istio.enabled }}
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "alertaggregator.fullname" . }}
spec:
  rules:
  - services:
    - {{ include "alertaggregator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
    constraints:
    - key: "destination.port"
      values: ["{{ .Values.service.port }}"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: {{ include "alertaggregator.fullname" . }}-grafana
  namespace: bootstrap
spec:
  rules:
  - services: ["*"]
    constraints:
    - key: "destination.labels[app]"
      values: ["grafana"]
{{ end }}